### PR TITLE
fix: Remove short options from conf.String() output

### LINKED ISSUE #48: Short params in conf.String() output
Hi,

I'm using `conf` in some projects and when application starts it outputs current settings in logs like this:
```
2025-04-12 14:41:43.835	INFO	container/container.go:92	Initial config:
    --build=v1.0.4-alpha, rev.1112222, build time: 2025-04-12 14:41:42
    --desc=app
-s, --srv-addr=0.0.0.0:33333
-a, --aux-addr=0.0.0.0:44444
-d, --template-dir=/usr/local/share/app/templates
-r, --read-timeout=5s
-w, --write-timeout=5s
-t, --shutdown-timeout=10s
2025-04-12 14:41:43.843	DEBUG	maxprocs/maxprocs.go:48	maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
2025-04-12 14:41:43.843	INFO	app/app.go:41	App start
```
I think short parameters in this context meaningless and would be nice to hide them. Something like this:
```
2025-04-12 14:41:43.835	INFO	container/container.go:92	Initial config:
    --build=v1.0.4-alpha, rev.1112222, build time: 2025-04-12 14:41:42
    --desc=app
    --srv-addr=0.0.0.0:33333
    --aux-addr=0.0.0.0:44444
    --template-dir=/usr/local/share/app/templates
    --read-timeout=5s
    --write-timeout=5s
    --shutdown-timeout=10s
2025-04-12 14:41:43.843	DEBUG	maxprocs/maxprocs.go:48	maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
2025-04-12 14:41:43.843	INFO	app/app.go:41	App start
```

But of course they must stay in help output. Would you accept such patch (+ sorting may be)?

### PR DESCRIPTION
**Pull request by nafigator**
fixes #48

Also added sorting.

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
Can't we do this without the extra dependencies?

**Comment by nafigator** [comment]
I would not like to write custom sorting. It adds more complexity I think. Those deps for sorting only.

**Comment by ardan-bkennedy** [comment]
I haven't looked at your code but the stdlib has sorting. I'll look at this during the week

**Comment by nafigator** [comment]
> I haven't looked at your code but the stdlib has sorting.

Thanks for the tip It works :)
Dependencies removed.

File: usage.go [hunk 1]
```diff
@@ -23,16 +21,19 @@ type sortedFields struct {
 	fields []Field
 }
 
-func (sf sortedFields) Len() int {
+func (sf *sortedFields) Len() int {
```
Comment (ardan-bkennedy) [inline usage.go:24]: This can stay value semantics since the backing array is not changing.

File: sources.go [hunk 2]
```diff
@@ -211,6 +211,11 @@ func flagUsage(fld Field) string {
 	return usage
 }
 
+// longOptInfo constructs a long option description string.
+func longOptInfo(fld Field) string {
```
Comment (ardan-bkennedy) [inline sources.go:215]: Why add a new function when `flagUsage` won't be used anymore? Why not change change the `flagUsage` function?

Comment (nafigator) [reply sources.go:215]: `flagUsage()` used in `writeOptions()` and it's functionality contains short flags for help output. So I decided to create a new function.

But I think both `flagUsage()` and `longOptInfo()` have two responsibilities. Would be better if they provided flag info only without formatting with spaces. But may be this is idea for next PR :)

File: usage.go (hunk 1 above)
Comment (nafigator) [reply usage.go]: Done.

File: sources.go (hunk 2 above)
Comment (ardan-bkennedy) [reply sources.go:215]: I hate these PR's because it's so hard to see everything.  I will have time on Friday to properly review and publish this.  Thanks
